RedRoverSchool/JenkinsQA_Python_2025_spring

.gitignore
tests/test_ivan_s_test.py

my first test

---

tests/test_ip_uitestingplayground.py

Add tests 
test_default_login_form_view()
test_success_login_message()

Add uitestingplayground.com Login Form Tests

---

tests/test_invalid_login_message_lk.py

New test_invalid_login_message_lk.py added

Added test_invalid_login_message_lk.py

---

tests/test_toolsqa_training.py

Selenium homework #1
Added test_toolsqa_training.py with 2 tests

Selenium HW #1 - add test_toolsqa_training.py

---

tests/test_alevtina_s.py

test_add_items_to_cart
test_remove_item_from_cart

add tests for saucedemo.com

---

tests/test_mv.py

add test Mikhail

---

tests/test_login_form.py

Added two tests from the lesson

two_tests_from_lesson

---

tests/test_gd_saucedemo.py

add login tests

---

tests/test_iana_s.py

1. Open https://demo.applitools.com
2. Fill in username
3. Fill in password
3.  Click Login button
4. Verify successful sign in

User login to the website

---

tests/test_cart_saucedemo.py

Tests added:
- test_add_product_to_cart()
- test_added_products_in_cart()
- test_products_displayed_in_checkout()
Two methods added: 
- login
- fill_checkout_information

Add Products in Cart and Checkout Tests

---

tests/test_mchuvashov_saucedemo_login.py

Added first test for saucedemo

Added first test for saucedemo

---

tests/test_oksanavk.py

Ov saucedemo

---

tests/test_demoblaze_incorrect_login_ak.py

add test for demoblaze login with incorrect password

---

tests/test_name_git.py

Привет. Проревьювьте пожалуйста мой тест.

"Sergey V - first commit"

---

.gitignore
tests/test_login_form.py

Исправленна орфографическая ошибка bottom -> button

fixed spelling in test_login_form.py and updated .gitignore

---

tests/test_vk_applitools_com.py

Add some UI tests of https://demo.applitools.com web site

add vk_applitools_com tests

---

tests/test_authentication_positive_lk.py

- Исключила бесполезный wait перед assert на URL
- Удалила неиспользуемую функцию registration_data
- Оставила custom_base_url как локальную фикстуру

Удалила дублирующую фикстуру driver и строку maximize_window

---

tests/test_dynamic_id.py

add test_dynamic_id.py

---

tests/test_alerts.py
tests/test_timo_l2.py

set options.page_load_strategy="eager"

Refactored test_alerts.py - set options.page_load_strategy="eager"

---

tests/test_alerts.py
tests/test_sauce_pp.py

It is the test_sauce_vn copied to test_sauce_pp, which run in incognito mode.

Example how run one test in incognito mode.

---

tests/test_ak_demoblaze.py

add test for demoblaze - login with invalid password

add test for demoblaze login with invalid password

---

tests/test_ak_demoblaze.py

refactor test_incorrect_password: reformat code, define wait, remove click with JS

refactor test_incorrect_password

---

tests/freestyle_project/test_create_new_project.py
tests/freestyle_project/test_enable_disable_freestyle_project.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/316

TC_02.001.01 | Freestyle Project Configuration> Enable or Disable the Project

---

tests/freestyle_project/conftest.py
tests/freestyle_project/test_enable_disable_freestyle_project.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/330

Refactor test_enable_disable_freestyle_project.py

---

tests/new_item/test_create_pipeline_item.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/335

TC_01.001.03 | New Item > Create New Item > Create Pipeline type Project

---

tests/new_item/test_display_of_project_type_list.py

Повторно открыт PR после случайного закрытия. [PR333](https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/pull/333)

Ir/tc 01.002.02

---

.github/diff-checker.sh
.github/workflows/continuous_integration.yml
.gitignore
conftest.py
requirements.txt
tests/freestyle_project/conftest.py
tests/freestyle_project/test_create_new_project.py
tests/freestyle_project/test_enable_disable_freestyle_project.py
tests/new_item/test_create_pipeline_item.py
tests/new_item/test_display_of_project_type_list.py

changes for running only changed tests
additional testing of this feature will be required
`pytest-picked`
to be merged on the top of screenshot changes

Only diff tests

---

tests/multibranch_pipeline_management/test_open_pipeline_from_dashboard.py

Added directory multibranch_pipeline_management.
Multibranch Pipeline Management Open Pipeline from the Dashboard Access Multibranch Project via Dashboard

TC_22.001.01 | Multibranch Pipeline Management > Open Pipeline from the Dashboard > Access Multibranch Project via Dashboard 

---

tests/freestyle_project/conftest.py
tests/freestyle_project/freestyle_data.py
tests/freestyle_project/test_description_freestyle_project.py
tests/freestyle_project/test_enable_disable_freestyle_project.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/366

TC_02.002.02 Freestyle Project Configuration> Project Description

---

tests/new_item/test_create_new_item.py

[TC_01.004.01 | New Item > Folder > Create a New Folder](https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/344)

TC_01.004.01 | New Item > Folder > Create a New Folder

---

tests/multibranch_pipeline_configuration/conftest.py
tests/multibranch_pipeline_configuration/mbp_data.py
tests/multibranch_pipeline_configuration/test_enabled_disabled_toggle.py

RF_06.001.01 | Multibranch Pipeline Configuration > Enable/Disable pipeline > Check the default state of the toggle

RF_06.001.01

---

tests/freestyle_project/freestyle_data.py
tests/freestyle_project/test_environment_freestyle_project.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/407
https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/417
https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/418

TC_02.005.01, TC_02.005.03, TC_02.005.04 Freestyle Project Configuration> Set up Environment

---

tests/freestyle_project/test_environment_freestyle_project.py
tests/freestyle_project/test_environment_set_freestyle_project.py
tests/freestyle_project/test_scm_freestyle_project.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/413

TC_02.005.02 | Freestyle Project Configuration> Set up Environment

---

tests/new_item/test_not_accept_spacial_characters.py

[TC_01.001.10 | New Item > Creatе a new item>Special characters (except underscores) should not be allowed.](https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/400)

TC_01.001.10 | New Item > Creatе a new item>Special characters (except underscores) should not be allowed.

---

tests/new_item/test_create_new_item.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/426

RF_01.004.01 | New Item > Folder > Create a New Folder

---

tests/new_item/data_structs.py
tests/new_item/new_item_steps.py
tests/new_item/test_copy_from.py

**ID: TC_01.003.02 | New Item > Copy from > Display dynamic dropdown in the "Copy from"**

TC_01.003.02 | New Item > Copy from > Display dynamic dropdown in the "Copy from" 

---

tests/Multi_configuration/test_set_description.py
tests/freestyle_project/conftest.py
tests/freestyle_project/test_description_freestyle_project.py
tests/freestyle_project/test_scm_freestyle_project.py

Refactoring for remove ruff check errors

Refactoring for remove ruff check errors

---

tests/new_item/data_structs.py
tests/new_item/test_special_chars.py

Test should verify that special chars used for New Item name are result in validation error

PR Special Chars validation (Olga 01.001.06)

---

tests/freestyle_project/test_environment_freestyle_project.py
tests/new_item/test_not_accept_spacial_characters.py
tests/pipeline/test_empty_description.py

TC_03.002.02 | Pipeline Configuration > Project Description > Allow empty description
https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/429

TC_03.002.02 | Allow empty description

---

tests/freestyle_project/conftest.py
tests/freestyle_project/test_description_freestyle_project.py
tests/freestyle_project/test_enable_disable_freestyle_project.py
tests/freestyle_project/test_freestyle_save_config.py
tests/freestyle_project/test_scm_freestyle_project.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/461

TC_02.008.01 | Freestyle Project Configuration> Save or Apply

---

tests/new_item/test_new_item_page_accessibility.py
tests/new_item/test_new_item_page_availability.py

Add a test for the New Item page accessibility

Add TC_01.001.05

---

tests/Multi_configuration/conftest.py
tests/Multi_configuration/test_edit_description.py
tests/Multi_configuration/test_set_description.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/468

RF_04.002.02 | Multi-configuration project Configuration > Edit Project Description

---

tests/freestyle_project/test_environment_freestyle_project.py

Refactoring test_tooltip_environment_items

---

tests/display_system_information/base_methods.py
tests/display_system_information/conftest.py
tests/display_system_information/locators.py
tests/display_system_information/system_information_page.py
tests/display_system_information/test_system_information_section.py

**TC_10.019.02 | Manage Jenkins > Display System Information > Show/hide all values on the "System Properties" tab**
**Preconditions:**
> The user is logged into Jenkins and located on the "System Information" page.
> The active tab is the "System Properties" tab, all values are hidden.
Description:
Verify that the show/hide all values buttons work properly on the "System Properties" tab.
**Steps:**
1. Click on the "Show values" button.
2. Check that all values have become visible.
3. Click on the "Hide values" button.
4. Check that all values have become hidden.
**Expected Result:**
All existing values on the "System Properties" tab became visible, and then hidden.
**Acceptance Criteria:**
The user should be able to show/hide values in System Properties and Environment Variables data.

TC_10.019.02 | Manage Jenkins > Display System Information > Show/hide all values on the "System Properties" tab

---

tests/display_system_information/test_system_information_section.py

**TC_10.019.03 | Manage Jenkins > Display System Information > Show/hide each single value on the "System Properties" tab**
**Preconditions:**
- The user is logged into Jenkins and located on the "System Information" page.
- The active tab is the "System Properties" tab, all values are hidden.
**Description:**
Verify that the individual show/hide value buttons work properly for each name on the "System Properties" tab.
**Steps:**
1. Click on the "Hidden value, click to show this value" button across the first name.
2. Check that this hidden value became visible.
3. Click on this visible value.
4. Check that this value has become hidden.
5. Repeat steps 1-4 for the rest names, one by one.
**Expected Result:**
All existing values on the "System Properties" tab, one by one, became visible …

TC_10.019.03 | Manage Jenkins > Display System Information > Show/hide each single value on the "System Properties" tab

---

tests/display_system_information/test_system_information_section.py

**TC_10.019.04 | Manage Jenkins > Display System Information > Show/hide all values on the "Environment Variables" tab**
**Preconditions:**
- The user is logged into Jenkins and located on the "System Information" page.
- The active tab is the "Environment Variables" tab, all values are hidden.
**Description:**
Verify that the show/hide all values buttons work properly on the "Environment Variables" tab.
**Steps:**
1. Click on the "Show values" button.
2. Check that all values have become visible.
3. Click on the "Hide values" button.
4. Check that all values have become hidden.
**Expected Result:**
All existing values on the "Environment Variables" tab became visible, and then hidden.
**Acceptance Criteria:**
The user should be able to show/hide values in System Properties and …

TC_10.019.04 | Manage Jenkins > Display System Information > Show/hide all values on the "Environment Variables" tab

---

tests/user/test_managing_account_description.py
tests/user/test_user_details_configuration.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/356

TC_15.002.02 | User > Managing Account Description > Profile Details Accessibilit

---

tests/freestyle_project/test_verify tooltip on hover.py

я понимаю что ничего не сделал , но смысл повторять будет написанное в фикстурах

Enable-ordisable-the-current

---

tests/user/test_user_details_configuration.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/520

TC_15.002.04 | User > Managing Account Description > Checking value of the Description field after saving new description

---

tests/freestyle_project/conftest.py
tests/freestyle_project/freestyle_data.py
tests/freestyle_project/test_build_triggers.py
tests/user/test_user_details_configuration.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/504

TC_02.004.003 | Freestyle Project Configuration > Build Triggers > User is able to trigger builds remotely with a valid Authentication Token

---

tests/pipeline/test_add_description_to_pipeline.py

RF_03.002.01 | Pipeline Configuration > Project Description > Add Description to Pipeline:
https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/528

RF_03.002.01 | Pipeline Configuration > Project Description > Add Description to Pipeline 

---

tests/wecome_dashboard/conftest.py

[RF_11.002.01 | Welcome Dashboard> Create a job > Verify that "New Item" page opens](https://github.com/orgs/RedRoverSchool/projects/8/views/1?pane=issue&itemId=108645542&issue=RedRoverSchool%7CJenkinsQA_Python_2025_spring%7C522)
fixed not used variable "wait5"

fixed not used wait5

---

tests/freestyle_project/test_build_steps.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/433

TC_02.006.01 | Freestyle Project Configuration > Build Steps > Build Steps availability

---

tests/new_folder_configuration/test_save_button.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/488

TC_05.004.01 | Folder Configuration > Save or Apply> Save button

---

tests/new_item/test_input_enter_name_is_displayed.py

TC_01.001.08 | New Item > Create a new item > Page has an Input field "Enter an item name"

Add TC_01.001.08

---

tests/wecome_dashboard/test_create_job.py

[TC_11.002.02 | Welcome Dashboard> Create a job > Verify user is able to create a job](https://github.com/orgs/RedRoverSchool/projects/8/views/1?pane=issue&itemId=107695599&issue=RedRoverSchool%7CJenkinsQA_Python_2025_spring%7C384)

Add TC_11.002.02 create_job

---

tests/new_item/test_create_folder.py

This test verifies the ability to create a new item of type "Folder" from the Jenkins Dashboard using the web interface.

TC_01.001.22 | New Item > Create a new item > Create Folder #556

---

pages/new_item_page.py
tests/new_item/data.py
tests/new_item/test_item_types.py

(https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/242?issue=RedRoverSchool%7CJenkinsQA_Python_2025_spring%7C505)

TC_01.001.20 | New Item > Creatе a new item>A list of available item types should be displayed.

---

pages/base_page.py
pages/manage_jenkins/status_information/system_information_page.py
tests/manage_jenkins/status_information/test_system_information.py

RF_10.019.03 | Manage Jenkins > Display System Information > "System Properties" tab - show/hide each single value

---

conftest.py
pages/manage_jenkins/status_information/system_information_page.py
tests/manage_jenkins/status_information/test_system_information.py

 RF_10.019.04 | Manage Jenkins > Display System Information > "Environment Variables" tab - show/hide all values

---

conftest.py
pages/manage_jenkins/status_information/system_information_page.py
tests/manage_jenkins/status_information/test_system_information.py

RF_10.019.06 | Manage Jenkins > Display System Information > "Plugins" tab - display information about installed plugins

---

conftest.py
pages/manage_jenkins/status_information/system_information_page.py
tests/manage_jenkins/status_information/data.py
tests/manage_jenkins/status_information/test_system_information.py

RF_10.019.07 | Manage Jenkins > Display System Information > "Memory Usage" tab - display graph according to the selected Timespan

---

conftest.py
pages/base_page.py
pages/manage_jenkins/status_information/system_information_page.py
tests/manage_jenkins/status_information/test_system_information.py

TC_10.019.08 | Manage Jenkins > Display System Information > "Thread Dumps" tab - open "Thread Dump" page

---

pages/base_page.py
pages/components/components.py
pages/login_page.py
pages/main_page.py
pages/ui_element.py
tests/sign_in_sign_out/data.py
tests/sign_in_sign_out/test_sign_out_windows.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/697
Added test_sign_out_windows.py - TC_08.002.01 | Sign in/out > Sign out

TC_08.002.01 | Sign in/out > Sign out

---

pages/freestyle_project_page.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/699
Refactoring freestyle_project_page.py for improve stability test_enable_after_disabled

RF_02.001.01 | Freestyle Project Configuration> Improved stability of test_enable_after_disabled

---

tests/new_item/data.py
tests/new_item/test_copy_from.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/670

TC_01.003.11 | New Item > Copy from > Display dynamic dropdown in the "Copy from" lowercase character

---

tests/new_item/conftest.py
tests/new_item/data.py
tests/new_item/test_copy_from.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/662

TC_01.003.10 | New Item > Copy from > Display multiple items in dynamic dropdown

---

conftest.py
pages/manage_jenkins/manage_jenkins_page.py
pages/manage_jenkins/status_information/load_statistics_page.py
tests/freestyle_project/test_build_triggers.py
tests/manage_jenkins/status_information/test_load_statistics.py

TC_10.022.01 | Manage Jenkins > Load Statistics > Open "Load statistics" Page

---

pages/multi_config_project_config_page.py
pages/multi_config_project_page.py
tests/multi_config/conftest.py
tests/multi_config/data.py
tests/multi_config/test_enable_disable_project.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/658

TC_04.001.03 | Multi-configuration project Configuration > Enable or Disable the Project > Display a warning message on the Project main page

---

tests/freestyle_project/conftest.py
tests/freestyle_project/test_enable_disable_freestyle_project.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/727
Refactoring test_enable_disable_freestyle_project.py to add allure reports

RF_02.001.01 | Freestyle Project Configuration> Enable or Disable the Project

---

pages/multi_config_project_config_page.py
pages/multi_config_project_page.py
pages/new_item_page.py
pages/ui_element.py
tests/multi_config/conftest.py
tests/multi_config/data.py
tests/multi_config/test_enable_disable_project.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/660

TC_04.001.04 | Multi-configuration project Configuration > Enable or Disable the Project > Disappear a warning message on the Project page

---

pages/main_page.py
tests/dashboard/test_view_all_jobs.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/757

TC_12.001.03 | Dashboard with the items > View All Jobs > Verification of default state for job without configuration

---

tests/freestyle_project/test_add_github_project.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/761

RF_02.009.01 | Freestyle Project Configuration > General project Settings > Add GitHub project

---

pages/new_item_page.py
pages/ui_element.py
tests/new_item/test_copy_from.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/768

RF_01.003.09 | New Item > Copy from > Select an item from the dynamic drop-down

---

pages/multi_config_project_config_page.py
pages/ui_element.py
tests/multi_config/data.py
tests/multi_config/test_enable_disable_project.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/542

TC_04.001.01 | Multi-configuration project Configuration > Enable or Disable the Project > Display the "Enable or disable the current project" tooltip

---

tests/new_item/conftest.py
tests/new_item/test_copy_from.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/776

RF_01.003.10 | New Item > Copy from > Display multiple items in dynamic dropdown

---

tests/new_item/data.py
tests/new_item/test_copy_from.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/777

RF_01.003.11 | New Item > Copy from > Display dynamic dropdown in the "Copy from" lowercase character

---

tests/pipeline/test_add_description_to_pipeline.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/809

RF_03.002.01 | Pipeline Configuration > Project Description > Add Description to Pipeline

---

pages/new_item_page.py
tests/new_item/test_item_type_check_descriptions.py
tests/new_item/test_select_an_item_type.py

add Allure https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/825

RF_01.002.02 | New Item > Select an Item type > Display of description each type

---

pages/pipeline_config_page.py
requirements.txt
tests/pipeline/pipeline_data.py
tests/pipeline/test_build_triggers.py
utils/assertions.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/833

TC_03.003.04 | Pipeline Configuration > Build Triggers > Displaying trigger checkbox labels

---

pages/pipeline_config_page.py
tests/pipeline/pipeline_data.py
tests/pipeline/test_build_triggers.py
utils/assertions.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/834

TC_03.003.05 | Pipeline Configuration > Build Triggers > Display of trigger checkboxes

---

pages/pipeline_config_page.py
tests/pipeline/conftest.py
tests/pipeline/test_build_triggers.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/845

TC_03.003.08 | Pipeline Configuration > Build Triggers > Disable trigger checkboxes by clicking labels

---

pages/pipeline_config_page.py
pages/ui_element.py
tests/pipeline/pipeline_data.py
tests/pipeline/test_build_triggers.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/847

TC_03.003.10 | Pipeline Configuration > Build Triggers > Helper tooltip help icon texts appear on hover

---

pages/pipeline_config_page.py
pages/ui_element.py
tests/pipeline/test_build_triggers.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/848

TC_03.003.11 | Pipeline Configuration > Build Triggers > Helper tooltip help icon disappears on mouse leave

---

pages/base_page.py
pages/pipeline_config_page.py
pages/pipeline_page.py
tests/pipeline/pipeline_data.py
tests/pipeline/test_build_triggers.py
utils/assertions.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/849

TC_03.003.12 | Pipeline Configuration > Build Triggers > Project creation with no triggers selected

---

.github/workflows/continuous_integration.yml
conftest.py
requirements.txt

Fix the screenshots attachment to Allure. 
Add Upload artifacts (screenshots) to the test run result.
Upgrade requests>=2.32.4 to remove  vulnerability alert

Fix screenshots attachment to Allure. Add Upload artifacts (screenshots) to test run result.

---

conftest.py
pages/main_page.py
tests/api/steps/jenkins_steps.py
tests/api/support/jenkins_client.py
tests/api/tests_ui/dashboard/conftest.py
tests/api/tests_ui/dashboard/data.py
tests/api/tests_ui/dashboard/test_view_all_jobs.py
tests/dashboard/test_view_all_jobs.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/877
Add `JenkinsClient` for API requests
Add `JenkinsSteps` for project creation
Refactor fixture to use API
Add XML test data

RF_12.001.03 | Dashboard with the items > View All Jobs > Verification of default state for job without configuration > API

---

pages/multi_config_project_config_page.py
tests/multi_configuration_project_configuration/conftest.py
tests/multi_configuration_project_configuration/test_env_section.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/883

TC_04.007.01 | Multi-configuration project Configuration > Configure Environment > Environment Section Is Displayed 

---

pages/multi_config_project_config_page.py
tests/multi_configuration_project_configuration/test_env_section.py

TC_04.007.02 | Multi-configuration project Configuration > Configure Environment >Delete_checkbox_is_selected

TC_04.007.02 | Multi-configuration project Configuration > Configure Environment >Delete_checkbox_is_selected

---

pages/multi_config_project_config_page.py
tests/multi_configuration_project_configuration/test_env_section.py

TC_04.007.06 | Multi-configuration project Configuration > Configure Environment > Terminate a build if it's stuck

TC_04.007.06 | Multi-configuration project Configuration > Configure Environment > Terminate a build if it's stuck

---

pages/multibranch_pipeline_config_page.py
tests/multibranch_pipeline_configuration/test_change_branch_sources.py

https://github.com/RedRoverSchool/JenkinsQA_Python_2025_spring/issues/882

TC_06.004.01 | Multibranch pipeline Configuration > Change Branch Sources > Verify Branch Sources section is available

---

tests/api/tests_ui/multiconfig_config/test_environment_visible.py

реализовала:
Подготовку проекта через API быстро и стабильно
Проверку UI секции Environment (по реальному отображению)
Структуру теста с Allure мета-данными: epic, story, title, testcase, link
Читаемый и поддерживаемый подход, идеально вписывающийся в Allure pipeline

TC_04.007.01_API | Multi-configuration project Configuration > Configure Environment > Environment Section Is Displayed

---

tests/api/tests_ui/multiconfig_config/conftest.py
tests/api/tests_ui/multiconfig_config/data.py
tests/api/tests_ui/multiconfig_config/test_environment_visible.py

Config класс — создала конфиг с нужными чекбоксами
Добавила  в Config в data.py: xml - config_with_environment_options_xml and
test_delete_checkbox_is_selected

TC_04.007.02 |API Multi-configuration project Configuration > Configure Environment >Delete_checkbox_is_selected

---

tests/api/tests_ui/multiconfig_config/conftest.py
tests/api/tests_ui/multiconfig_config/data.py
tests/api/tests_ui/multiconfig_config/test_environment_visible.py

"Terminate a build " is selected when configuring a Multi-configuration project in Jenkins in the “Environment” section

API TC_04.007.06 | Multi-configuration project Configuration > Configure Environment > Terminate a build if it's stuck
